### ISSUE TITLE
Crash and error log

### ISSUE THREAD

**Issue by ProMcTagonist** [Impyy/Toxy#82] opened 2016-02-05 08:16 UTC
From IRC.

    <Guest16126> my software shutdown, please help me solve this error: http://pastebin.com/kVVqaLYE
    <Guest16126> can anybody help me

http://pastebin.com/kVVqaLYE

**Comment by hypereddie** [comment] 2016-02-05 18:14
Exception message translated to English
```
Appendix: powershell_ise.exe
Platform Version: v4.0.30319
Description. The process was terminated due to an unhandled exception.
Exception Details: System.AccessViolationException
Stack:
```

**Comment by Impyy** [comment] 2016-02-05 20:07
This guy is trying to use SharpTox in powershell and that 'Стек' trace is kind of useless as it's either a crash in toxcore or a crash caused by one of the registered callbacks. I need more information.

Anyways, I'll close this as it's not an issue in Toxy.

**Closed by Impyy** 2016-02-05 20:07 UTC

**Comment by Impyy** [comment] 2016-02-05 20:25
I noticed that he tried to ask me about this on IRC, but I was away.
He can send me an email at impyy@tox.chat and I'll try to help him.
